export enum STRINGS {
    API_LOGIN_URL = 'http://localhost:8081/api/users/login',
    API_REGISTER_URL = 'http://localhost:8081/api/users/registration',
    API_USER_GET_USERNAME_BY_UUID = 'http://localhost:8081/api/users/username/',
    API_USER_NAME_URL = 'http://localhost:8081/api/users/username/',
    API_LIBRARY = 'http://localhost:8081/api/users/library/',
    API_USER_BUY_GAMES_FROM_CART = 'http://localhost:8081/api/users/cart/',
    API_USER_GET_USER_DATA = 'http://localhost:8081/api/users/profile/',
    API_USER_UPDATE_USER_DATA = 'http://localhost:8081/api/users/profile/update',
    API_USER_UPDATE_USER_BALANCE = 'http://localhost:8081/api/users/profile/balance/',
    API_ALL_GAMES_FOR_SHOP = 'http://localhost:8081/api/games/shop/',
    API_GAMES_DETAILS = 'http://localhost:8081/api/games/',
    API_GAMES_GET_ALL_CART_GAMES = 'http://localhost:8081/api/games/cart',
    API_GAMES_GET_ALL_GENRES = 'http://localhost:8081/api/games/genres',
    API_GAMES_FILTER_BY_ATTRIBUTE = 'http://localhost:8081/api/games/shop/filter',
    API_GAMES_MIN_MAX_PRICE = 'http://localhost:8081/api/games/shop/min-max-price',
    STEAM_GE_TO_APP_STORE ='https://store.steampowered.com/app/',
    HEADER_HEIGHT_FOR_CONTENT = 54,
    HEADER_HEIGHT_FOR_LEFT_SIDE = 153,
}